# Generated by Django 4.1 on 2022-08-30 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('nombre', models.CharField(max_length=30)),
                ('DNI', models.IntegerField(primary_key=True, serialize=False)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFinal.author')),
                ('fuentes', models.ManyToManyField(to='AppFinal.source')),
            ],
        ),
    ]
